name: Code Analysis

on:
  push:
      branches: [ "main", "development", "test", "acceptance" ]
  pull_request:
      branches: [ "main", "development", "test", "acceptance" ]

jobs:
  code-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Build with Maven and Run PMD
      run: mvn clean verify site -Dmaven.test.skip=true

    - name: Upload PMD report
      uses: actions/upload-artifact@v2
      with:
        name: pmd-report
        path: target/site/pmd.xml
