name: Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Install security scanner
        run: |
          npm install -g snyk

      - name: Run security scan
        run: snyk test --all-projects --json > snyk_report.json

      - name: Upload security scan report
        uses: actions/upload-artifact@v2
        with:
          name: security-scan-report
          path: snyk_report.json
