name: Security Scan

on:
  push:
    branches: [ "main", "development", "test", "acceptance" ]
  pull_request:
    branches: [ "main", "development", "test", "acceptance" ]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 19

      - name: Install security scanner
        run: |
          npm install -g snyk

      - name: Run OWASP Dependency-Check
        run: mvn org.owasp:dependency-check-maven:7.1.0:check
