name: Publish to Google Drive
on:
  push:
    branches: [ "acceptance" ]
  pull_request:
    branches: [ "acceptance" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log recent commit
        run: git log -1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'oracle'
          cache: maven

      - name: Build with Maven
        run: mvn clean verify

      - name: Zip report directory
        run: zip -r jabberpoint.zip target/*.jar

      - name: Upload to G-Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          filename: "jabberpoint.zip"
          folderId: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          overwrite: "true" # optional boolean
