name: Upload Jar to GCS

on:
  push:
    branches: [ "acceptance" ]

jobs:
  upload:
    name: Upload Jar to GCS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build with Maven
        run: mvn clean verify

      - name: Zip report directory
        run: zip -r jabberpoint.zip target/*.jar

      - name: Upload to G-Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          filename: "jabberpoint.zip"
          overwrite: "true" 
